name: Run With Ubuntu 20.04 or Ubuntu Latest

on:
  schedule:
    - cron: "*/3 * * * *" # every 3 minutes

jobs:
  run:
    runs-on: ubuntu-20.04

    steps:
      - name: Update timestamp
        run: curl "https://api-benchmark-cron.vercel.app/ping?id=github-ubuntu-20.04"
