name: Run With Ubuntu 22.04

on:
  schedule:
    - cron: "*/3 * * * *" # every 3 minutes

jobs:
  run:
    runs-on: ubuntu-22.04

    steps:
      - name: Update timestamp
        run: curl https://api-benchmark-cron.vercel.app/ping?id=github-ubuntu-22.04
