name: Run With Ubuntu 20.04

on:
  schedule:
    - cron: "* */3 * * *"

jobs:
  run:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Update timestamp
        run: ./timestamp.sh >> ubuntu-20.04.txt

      - name: Git Add and Commit
        run: |
          git config --local user.email "81743021+mzakiyuddin@users.noreply.github.com"
          git config --local user.name "mzakiyuddin"
          git add . 
          now=$(date)
          git commit -m "feat: update data $now"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
